name: Kamal CI

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      KAMAL_REGISTRY_USERNAME: thr3a
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary
          name: id_ed25519
          config: ${{ secrets.SSH_CONFIG }}

      - name: Install cloudflared
        run: |
          lastest_version=$(curl -s $GITHUB_API_URL/repos/cloudflare/cloudflared/releases/latest | jq -r '.tag_name')
          mkdir -p /tmp/cloudflared
          curl -sL -o /tmp/cloudflared/cloudflared $GITHUB_SERVER_URL/cloudflare/cloudflared/releases/download/$lastest_version/cloudflared-linux-amd64
          chmod +x /tmp/cloudflared/cloudflared
          /tmp/cloudflared/cloudflared --version

      - name: ssh test
        run: |
          ssh ubuntu01.turai.work date

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: thr3a
          password: ${{ env.KAMAL_REGISTRY_PASSWORD }}

      - name: Set up Kamal
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Install Kamal
        run: gem install kamal

      # - name: Build and Push Docker Image
      #   run: kamal build push
      - name: Deploy to Server
        run: |
          ssh ubuntu01.turai.work date
          kamal deploy
        # run: kamal deploy
