name: Kamal CI

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      KAMAL_REGISTRY_USERNAME: thr3a
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: thr3a
          password: ${{ env.KAMAL_REGISTRY_PASSWORD }}

      # - name: Expose GitHub Runtime for cache
      #   uses: crazy-max/ghaction-github-runtime@v3

      - name: Set up Kamal
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Install Kamal
        run: gem install kamal

      - name: Build and Push Docker Image
        run: kamal build push

      # - name: Deploy to Server
      #   run: kamal deploy
      #   # run: kamal deploy -d production
      #   env:
      #     KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
